name: Install tools
description: Install pnpm, Node.js specified by .tool-versions

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Get node version from volta
      id: get-node-version
      uses: keita-hino/get-node-version-from-volta@main
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.get-node-version.outputs.nodeVersion }}
    
