name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: Install Dependencies
        run: pnpm install --dev

      - name: Lint with Prettier
        run: pnpm lint
